-- Run this in Supabase > SQL Editor.
-- It creates protected content tables and a private document bucket.

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  role text not null,
  name text not null,
  email text,
  display_order integer not null default 100
);

alter table public.notices enable row level security;
alter table public.documents enable row level security;
alter table public.contacts enable row level security;

-- Signed-in residents may read portal content.
drop policy if exists "Residents read notices" on public.notices;
create policy "Residents read notices" on public.notices
  for select to authenticated using (true);

drop policy if exists "Residents read documents" on public.documents;
create policy "Residents read documents" on public.documents
  for select to authenticated using (true);

drop policy if exists "Residents read contacts" on public.contacts;
create policy "Residents read contacts" on public.contacts
  for select to authenticated using (true);

-- Private storage bucket for documents.
insert into storage.buckets (id, name, public)
values ('residents-documents', 'residents-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "Residents read stored documents" on storage.objects;
create policy "Residents read stored documents" on storage.objects
  for select to authenticated
  using (bucket_id = 'residents-documents');

-- Example starter content (optional):
insert into public.notices (title, body)
select 'Welcome to the residents portal', 'Association updates and important notices will appear here.'
where not exists (select 1 from public.notices);

insert into public.contacts (role, name, email, display_order)
select 'Chair', 'Committee Chair', 'chair@example.org', 10
where not exists (select 1 from public.contacts);
